package domain.map;

public enum PathType {
	HORIZONTAL_MIDDLE, HORIZONTAL_END_LEFT, HORIZONTAL_END_RIGHT, 
	VERTICAL_MIDDLE, VERTICAL_END_LEFT, VERTICAL_END_RIGHT,
	RIGHT, LEFT, TOP, BOTTOM, BOTTOMRIGHT, BOTTOMLEFT, TOPLEFT, TOPRIGHT
}
