name: Build Windows App Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Install Maven
      run: choco install maven --no-progress

    - name: Build shaded JAR
      run: mvn clean package

    - name: Download JavaFX SDK
      run: |
        curl -L -o javafx.zip https://download2.gluonhq.com/openjfx/21.0.7/openjfx-21.0.1_windows-x64_bin-sdk.zip
        unzip javafx.zip -d javafx-sdk

    - name: Create custom runtime image
      run: >
        jlink
        --module-path "javafx-sdk/javafx-sdk-21.0.7/lib;${{ env.JAVA_HOME }}/jmods"
        --add-modules java.base,javafx.controls,javafx.fxml
        --output runtime

    - name: Package App Image
      run: >
        jpackage
        --type app-image
        --input target
        --name KuTowerDefense
        --main-jar kutowerdefense.jar
        --main-class ui.Main
        --runtime-image runtime
        --dest dist
        --icon src/main/resources/icon.ico
        --module-path javafx-sdk/javafx-sdk-21.0.1/lib
        --add-modules javafx.controls,javafx.fxml
